### ISSUE TITLE
KeyError 'mets' on collection-detail

### ISSUE THREAD

**Issue by gjost** [denshoproject/ddr-cmdln#235]
sara.beckman [2023-08-11] Dina got a Failure message for a file import. I just took a look at the file CSV and didn't find any glaring errors, but when I went to Editor to look at the collection I got a KeyError page when trying to navigate to the collection page.

> Dina - then if I click on log it gives me 404 file not found.  I'm sure I coded something wrong in the CSV, so I will rework it next week.

```
Environment:

Request Method: GET
Request URL: http://192.168.56.101/ui/entity/ddr-densho-466/

Django Version: 4.1.9
Python Version: 3.9.2
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'bootstrap_pagination',
 'gunicorn',
 'rest_framework',
 'sorl.thumbnail',
 'ddrlocal',
 'storage',
 'webui',
 'namesdb_public')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')

Traceback (most recent call last):
  File "/opt/ddr-local/venv/ddrlocal/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/opt/ddr-local/venv/ddrlocal/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/ddr-local/ddrlocal/storage/decorators.py", line 83, in inner
    return func(request, *args, **kwargs)
  File "/opt/ddr-local/ddrlocal/webui/views/entities.py", line 208, in detail
    entity = Entity.from_identifier(Identifier(eid))
  File "/opt/ddr-local/ddrlocal/webui/models.py", line 739, in from_identifier
    return from_json(Entity, identifier.path_abs('json'), identifier)
  File "/opt/ddr-local/venv/ddrlocal/lib/python3.9/site-packages/ddr_cmdln-5.8.1-py3.9.egg/DDR/models/common.py", line 832, in from_json
    document = model(os.path.dirname(json_path), identifier=identifier)
  File "/opt/ddr-local/venv/ddrlocal/lib/python3.9/site-packages/ddr_cmdln-5.8.1-py3.9.egg/DDR/models/entity.py", line 112, in __init__
    self.mets_path_rel = i.path_rel('mets')
  File "/opt/ddr-local/venv/ddrlocal/lib/python3.9/site-packages/ddr_cmdln-5.8.1-py3.9.egg/DDR/identifier.py", line 1323, in path_rel
    filename = ADDITIONAL_PATHS[self.model][append]

Exception Type: KeyError at /ui/entity/ddr-densho-466/
Exception Value: 'mets'
```

**Comment by gjost** [comment]
Looks like user error in URL field.
